- id: doi:10.1016/j.seppur.2025.133908
  title: "Tailoring amine activators in MDEA/NHD/H2O biphasic absorbents for energy-efficient CO<sub>2</sub> capture: Mechanistic insights into polarity-driven phase separation and multi-component synergy"
  authors:
  - Dingkai Hu#
  - \textbf{Bohak Yoon#}
  - Yanlong Hu
  - Dezhi Cao
  - Qiang Wang
  - Bin Wang
  - Shijian Lu
  image: ../images/research/yoon-group-research-2025-18.png

- id: doi:10.1021/acssuschemeng.5c02555
  title: "Quantum Chemistry-Guided Machine Learning for Accelerated Design of CO<sub>2</sub>-Solubilizing Deep Eutectic Solvents"
  authors:
  - Dingkai Hu
  - Dezhi Cao
  - Shi-jian Lu
  - Qiang Wang\*
  - Bohak Yoon\*
  image: ../images/research/yoon-group-research-2025-17.png

- id: doi:10.1021/acs.jpclett.5c00349
  image: ../images/research/yoon-group-research-2025-16.png

- id: doi:10.1002/advs.202406281
  title: "Impact of Side Chains in 1\u2010<i>n</i>\u2010Alkylimidazolium Ionomers on Cu\u2010Catalyzed Electrochemical CO<sub>2</sub> Reduction"
  authors:
  - Young In Song#
  - Bohak Yoon#
  - Chanwoo Lee
  - Dogyeong Kim
  - Man Ho Han
  - Hyungu Han
  - Woong Hee Lee
  - Da Hye Won
  - Jung Kyu Kim
  - Hyo Sang Jeon
  - Jai Hyun Koh
  image: ../images/research/yoon-group-research-2024-15.png

- id: doi:10.1021/jacs.3c11808
  image: ../images/research/yoon-group-research-2024-14.png

- id: doi:10.1021/jacs.3c03613
  image: ../images/research/yoon-group-research-2023-13.png
  
- id: doi:10.1016/j.seppur.2022.122856
  image: ../images/research/yoon-group-research-2023-12.png

- id: doi:10.1016/j.jece.2022.108987
  image: ../images/research/yoon-group-research-2022-9.png

- id: doi:10.1016/j.seppur.2022.121861
  image: ../images/research/yoon-group-research-2022-10.png

- id: doi:10.1021/acssuschemeng.2c02502
  image: ../images/research/yoon-group-research-2022-8.png

- id: doi:10.1016/j.cej.2022.136674
  authors:
  - Qinlan Luo#
  - Bohak Yoon#
  - Hongxia Gao
  - Juan Lv
  - Gyeong S. Hwang
  - Min Xiao
  - Zhiwu Liang
  image: ../images/research/yoon-group-research-2022-7.png

- id: doi:10.26153/TSW/42585
  image: ../images/research/yoon-group-research-2022-11.png

- id: doi:10.1021/acs.iecr.1c04987
  image: ../images/research/yoon-group-research-2022-5.png

- id: doi:10.1002/aic.17701
  authors:
  - Qinlan Luo#
  - Rui Dong#
  - Bohak Yoon#
  - Hongxia Gao
  - Mengjie Chen
  - Gyeong S. Hwang
  - Zhiwu Liang
  image: ../images/research/yoon-group-research-2022-6.png

- id: doi:10.1021/acs.energyfuels.1c02361
  image: ../images/research/yoon-group-research-2021-4.png

- id: doi:10.1021/acssuschemeng.0c07203
  image: ../images/research/yoon-group-research-2020-3.png

- id: doi:10.1039/d0cp02178d
  image: ../images/research/yoon-group-research-2020-2.png

- id: doi:10.1039/c9cp04518j
  authors:
  - Bohak Yoon
  - Haley M. Stowe
  - Gyeong S. Hwang
  image: ../images/research/yoon-group-research-2019-1.png



#- id: doi:10.1371/journal.pcbi.1007128
#  type: paper
#  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#  date: 2020-12-4
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: greenelab/meta-review

#- id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
